# Default values for ctrader umbrella chart

reader:
  image:
    repository: ghcr.io/wcraigtrader/reader
    tag: latest

writer:
  image:
    repository: ghcr.io/wcraigtrader/writer
    tag: latest

# Common RabbitMQ settings can be set here and passed through to subcharts
rabbitmq:
  host: rabbitmq
  port: 5672
  username: user
  password: "queuemunicate"
  queue: messages

  # Bitnami RabbitMQ chart mapping
  auth:
    username: user
    password: "queuemunicate"
    # Erlang cookie value; change if you need clustering
    erlangCookie: "queuemunicate"
