replicaCount: 1

image:
  repository: ghcr.io/wcraigtrader/webapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 9000

env:
  READER_URL: "http://reader:9002/messages"
