spring.application.name=ctrader-writer
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

ctrader.queue=${CTRADER_QUEUE:ctrader.queue}
app.version=${APP_VERSION:0.1.0}
publish.rate.ms=${PUBLISH_RATE_MS:1000}
