spring.application.name=helmtest-writer
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

helmtest.queue=${HELMTEST_QUEUE:messages}
app.version=${APP_VERSION:0.1.0}
publish.rate.ms=${PUBLISH_RATE_MS:1000}
