apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "writer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "writer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "writer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "writer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "writer.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: SPRING_RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.username | quote }}
            - name: SPRING_RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.password | quote }}
            - name: CTRADER_QUEUE
              value: {{ .Values.rabbitmq.queue | quote }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
